---
- name: Create Alacritty configuration directory
  file:
    path: "{{ ansible_env.HOME }}/.config/alacritty"
    state: directory
    mode: '0755'

- name: Copy default.toml configuration file
  copy:
    src: "alacritty/default.toml"
    dest: "{{ ansible_env.HOME }}/.config/alacritty/default.toml"

- name: Copy alacritty.toml configuration file
  copy:
    src: "alacritty/alacritty.toml"
    dest: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.toml"

- name: Copy Tokyo Night theme configuration file
  copy:
    src: "alacritty/theme.toml"
    dest: "{{ ansible_env.HOME }}/.config/alacritty/theme.toml"

- name: Copy font configuration file
  copy:
    src: "alacritty/font.toml"
    dest: "{{ ansible_env.HOME }}/.config/alacritty/font.toml"

- name: Copy font-size configuration file
  copy:
    src: "alacritty/font-size.toml"
    dest: "{{ ansible_env.HOME }}/.config/alacritty/font-size.toml"
