---
- name: Install vscode plugins
  shell:  "code --install-extension {{ item }}"
  args:
    executable: /bin/bash
  with_items:
    - ms-vscode.cpptools
    - hashicorp.terraform
    - rust-lang.rust-analyzer
    - ms-vscode.cpptools-extension-pack
    - ms-vscode.cpptools-themes
    - ms-vscode.cmake-tools
    - ms-vscode-remote.remote-containers
    - ms-azuretools.vscode-docker
    - dbaeumer.vscode-eslint
    - GitHub.copilot
    - GitHub.copilot-chat
    - golang.go
    - k--kato.intellij-idea-keybindings
    - ms-vscode.makefile-tools
    - esbenp.prettier-vscode
    - ms-python.vscode-pylance
    - ms-python.python
    - ms-python.debugpy
    - jsjlogin.zxbasic
    - enkia.tokyo-night

- name: Set workbench.colorTheme to "patata" in VSCode settings.json
  lineinfile:
    path: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/settings.json"
    regexp: '"workbench.colorTheme": ".*"'
    line: '"workbench.colorTheme": "Tokyo Night"'
    backrefs: yes
