---
# List of Homebrew packages to install
brew_casks:
  - 1password
  - 1password-cli
  - calibre
  - angry-ip-scanner
  - balenaetcher
  - applepi-baker
  - sdformatter
  - caffeine
  - cleanmymac
  - cyberduck
  - keka
  - rar
  - obsidian
  - espanso
  - tailscale
  - vlc
  - phoenix-slides
  - alfred
  # Browsers
  - firefox
  - tor-browser
  - google-chrome
  # Downloads
  - jdownloader
  - transmission
  # Games
  - steam
  - openemu
  # Dev tools
  - postman
  - vagrant
  - virtualbox
  - docker
  - visual-studio-code
  - intellij-idea-ce
  # Communication
  - slack
  - skype
  - zoom
  # Customizations
  - aerospace
  # Terminal
  - wezterm
  - font-hack-nerd-font
  - font-jetbrains-mono

mas_app_ids:
  - 463541543 # Gemini
  - 1474276998 # HP Smart
  - 405399194 # Kindle
  - 905953485 # NordVPN
  - 407963104 # Pixelmator
  - 568494494 # Pocket
  - 904280696 # Things
  - 1147396723 # WhatsApp