---
- name: Check if Neovim configuration directory exists
  stat:
    path: "{{ ansible_env.HOME }}/.config/nvim"
  register: nvim_config_dir

- name: Clone LazyVim starter if nvim config does not exist
  git:
    repo: https://github.com/LazyVim/starter
    dest: "{{ ansible_env.HOME }}/.config/nvim"
  when: not nvim_config_dir.stat.exists

- name: Disable update notification popup in starter config
  lineinfile:
    path: "{{ ansible_env.HOME }}/.config/nvim/lua/config/lazy.lua"
    regexp: 'checker = { enabled = true }'
    line: 'checker = { enabled = true, notify = false }'
  when: not nvim_config_dir.stat.exists

- name: Create directory for plugin after scripts
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim/plugin/after"
    state: directory
    mode: '0755'
  when: not nvim_config_dir.stat.exists

- name: Copy transparency.lua to plugin after directory
  copy:
    src: configs/neovim/transparency.lua
    dest: "{{ ansible_env.HOME }}/.config/nvim/plugin/after/transparency.lua"
  when: not nvim_config_dir.stat.exists

- name: Copy Tokyo Night theme configuration
  copy:
    src: configs/neovim/theme.lua
    dest: "{{ ansible_env.HOME }}/.config/nvim/lua/plugins/theme.lua"
  when: not nvim_config_dir.stat.exists

- name: Copy lazyvim.json to Neovim configuration
  copy:
    src: configs/neovim/lazyvim.json
    dest: "{{ ansible_env.HOME }}/.config/nvim/lazyvim.json"
  when: not nvim_config_dir.stat.exists
