---
- name: Create Zellij themes directory
  file:
    path: "{{ ansible_env.HOME }}/.config/zellij/themes"
    state: directory
    mode: '0755'

- name: Copy Zellij config.kdl
  copy:
    src: "configs/zellij/config.kdl"
    dest: "{{ ansible_env.HOME }}/.config/zellij/config.kdl"

- name: Copy Tokyo Night theme configuration file for Zellij
  copy:
    src: "configs/zellij/tokyo-night.kdl"
    dest: "{{ ansible_env.HOME }}/.config/zellij/themes/tokyo-night.kdl"
